Feature/SVModulator
NicolaiFransen/SemesterProjectPED2 pull request #24
Opened 2019-04-16 12:02 UTC by murgui

First draft - Missing to test. But I dont even know how I will test yet.

2019-04-16 14:48 UTC, NicolaiFransen commented on Software/Development/SemesterProject/App/Include/SVModulator.h
> +}alphaBetaObject;
Remember to remove this

2019-04-16 15:03 UTC, NicolaiFransen requested changes
As most of it was copy-paste, it looks great. The only problem is the interface function

2019-04-16 15:03 UTC, NicolaiFransen commented on Software/Development/SemesterProject/App/SVModulator.c
> +    Vdc = getDCLinkMeasurement();
As we talked about this will have to be changed when the interface functions are updated

2019-04-16 15:03 UTC, NicolaiFransen commented on Software/Development/SemesterProject/App/SVModulator.c
> +    Vdc = getDCLinkMeasurement();
So for this to work now you need to add the gain of the sensor network

2019-04-29 11:28 UTC, NicolaiFransen approved these changes

2019-04-29 11:44 UTC, AitorTeran approved these changes
Good job Nicos!
Ship it!!¡

2019-04-29 12:33 UTC, murgui reviewed
Great, great code my friend.

(¡¡ASIDE OF JOKES, GOOD CATCH!!)

2019-04-29 12:33 UTC, murgui commented on Software/Development/SemesterProject/App/SVModulator.c
> +    Vdc = 32.0;//testing here getDCLinkMeasurement();
You are better than that Nicolai

2019-04-29 12:33 UTC, murgui commented on Software/Development/SemesterProject/App/closedLoopControl.c
> +/*
This file must be removed

2019-04-29 12:33 UTC, murgui commented on Software/Development/SemesterProject/App/signalGeneration.c
> +#define signalGenerationEnabled
This file must be excluded from compilation by comenting the define

2019-04-29 14:13 UTC, NicolaiFransen commented on Software/Development/SemesterProject/App/SVModulator.c
> +    Vdc = 32.0;//testing here getDCLinkMeasurement();
🤷‍♂

2019-04-29 14:43 UTC, merged