Feature/controller
NicolaiFransen/SemesterProjectPED2 pull request #29
Opened 2019-04-22 14:17 UTC by NicolaiFransen

Creates the PI objects and calcualtes the current reference values

2019-04-23 12:28 UTC, AitorTeran approved these changes
Looks good¡¿

2019-04-24 07:40 UTC, murgui requested changes
Nice job.

I think there should be an external interface for resetting integrators. This interface would be used when an error is detected, then after the user ACK, the system will start from scratch.

2019-04-24 07:40 UTC, murgui commented on Software/Development/SemesterProject/App/controller.c
> +    PIObject_Constructor(&PIControllerList.IdController, KP_ID, KI_ID, CURRENT_LIMIT, 0);
![image](https://user-images.githubusercontent.com/29175623/56640825-3866a000-6674-11e9-92da-857fdf6aa0e0.png)

I like constructor's variable names 👍

2019-04-25 07:44 UTC, NicolaiFransen commented
I have created the functions to reset the integrators. 
For now im calling it while in the system is in standby state. Then we do the reset both when an error happens and when you change the reference.

2019-04-25 13:35 UTC, murgui approved these changes
¡¡¡¡SHIP IT!!!!

2019-04-25 13:46 UTC, merged