Feature/uart print
NicolaiFransen/SemesterProjectPED2 pull request #33
Opened 2019-04-30 13:28 UTC by NicolaiFransen

2019-04-30 13:57 UTC, murgui requested changes
Good.

2019-04-30 13:57 UTC, murgui commented on Software/Development/SemesterProject/System/scheduler.c
> +{
Nice Empty task

2019-04-30 13:57 UTC, murgui commented on Software/Development/SemesterProject/System/scheduler.c
> +    UARTIntPrint("Vdc ", (int)(getDCLinkMeasurement() * 100));
maybe everything should be commented?

2019-05-01 12:05 UTC, murgui approved these changes
Go for it (if it is not crashing too much)

2019-05-01 12:06 UTC, murgui commented
I think that in addition to have the task, a short description including the character limitation should be added. So for example saying it was tested that with 50 characters printed in the function, it was not crashing.

2019-05-01 12:08 UTC, AitorTeran reviewed
mmmm

2019-05-01 12:08 UTC, AitorTeran commented on Software/Development/SemesterProject/System/Include/scheduler.h
> +void task1ms(void);
Maybe 1ms is too much, during tests, we were printing at 10ms and it was crashing (true, with the long names but still....)

2019-05-01 12:08 UTC, AitorTeran commented on Software/Development/SemesterProject/System/Include/scheduler.h
> +void task1ms(void);
An idea is to call the task something like taskUART(void) and then set the cyclicity to a constant that we can change depending on the case...

2019-05-01 12:08 UTC, AitorTeran commented on Software/Development/SemesterProject/System/scheduler.c
> +    printUART();
so printing uart both every 1ms and 10ms?

2019-05-03 07:37 UTC, merged